version: "3.9"

services:
  database: 
    image: mysql
    container_name: ecommerce_gama_db
    restart: unless-stopped

    ports: 
      - 3306:3306
    environment:
      - MYSQL_USERNAME=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=ecommerce_gama



